//! Render resolved operations as Hurl files and a suite README.

use std::collections::{BTreeMap, HashSet};
use std::fmt::Write as _;

use serde_json::Value;

use crate::error::{Error, Result};
use crate::sample::{
    base_content_type, choose_media, has_explicit_sample, is_json_content_type, sample_media,
    sample_schema, value_to_wire_string,
};
use crate::spec::{self, Document, Operation, Parameter};
use crate::VERSION;

#[derive(Debug, Clone)]
pub(crate) struct RenderedFile {
    pub name: String,
    pub body: String,
    pub method: String,
    pub path: String,
    pub operation_id: Option<String>,
    pub summary: Option<String>,
}

pub(crate) fn render_suite(document: &Document) -> Result<Vec<RenderedFile>> {
    let names = file_names(document);
    let mut files = Vec::with_capacity(document.operations.len());
    for (operation, name) in document.operations.iter().zip(names) {
        let body = render_operation(document, operation, &name)
            .map_err(|err| err.in_context(&format!("{} {}", operation.method, operation.path)))?;
        files.push(RenderedFile {
            name,
            body,
            method: operation.method.clone(),
            path: operation.path.clone(),
            operation_id: operation.operation_id.clone(),
            summary: operation
                .summary
                .as_deref()
                .or(operation.description.as_deref())
                .map(one_line),
        });
    }
    Ok(files)
}

pub(crate) fn render_readme(document: &Document, files: &[RenderedFile]) -> String {
    let hint = spec::server_hint(&document.servers);
    let base_url = hint.as_deref().unwrap_or("https://example.com");
    let mut readme = String::new();
    let _ = writeln!(readme, "# Hurl contract suite");
    let _ = writeln!(readme);
    let _ = writeln!(
        readme,
        "Generated by [spechurl](https://github.com/hamarshehmhmd/spechurl) {VERSION} from `{}`.",
        document.source_name
    );
    let _ = writeln!(
        readme,
        "Do not edit these files by hand. Change the OpenAPI document and run `spechurl generate` again."
    );
    let _ = writeln!(
        readme,
        "`spechurl check` fails if this directory drifts from the spec."
    );
    let _ = writeln!(readme);
    let _ = writeln!(readme, "| | |");
    let _ = writeln!(readme, "| --- | --- |");
    let _ = writeln!(readme, "| Spec | {} |", document.title);
    let _ = writeln!(readme, "| OpenAPI | {} |", document.openapi);
    let _ = writeln!(readme, "| Version | {} |", document.version);
    let _ = writeln!(readme, "| Server hint | `{base_url}` |");
    let _ = writeln!(readme);
    let _ = writeln!(readme, "## Run");
    let _ = writeln!(readme);
    let _ = writeln!(
        readme,
        "Install [Hurl](https://hurl.dev/docs/installation.html), then from this directory:"
    );
    let _ = writeln!(readme);
    let _ = writeln!(readme, "```bash");
    let _ = writeln!(readme, "hurl --variable base_url={base_url} --test .");
    let _ = writeln!(readme, "```");
    let _ = writeln!(readme);
    let _ = writeln!(
        readme,
        "`base_url` is the server origin and any base path, with no trailing slash. Request paths come from the spec."
    );
    if hint.is_none() {
        let _ = writeln!(readme);
        let _ = writeln!(
            readme,
            "The spec did not include a concrete `http` or `https` server URL, so the command above uses `https://example.com` as a placeholder."
        );
    }
    let _ = writeln!(readme);
    let _ = writeln!(readme, "## Operations");
    let _ = writeln!(readme);
    let _ = writeln!(readme, "| File | Method | Path | Operation | Summary |");
    let _ = writeln!(readme, "| --- | --- | --- | --- | --- |");
    for file in files {
        let operation = file.operation_id.as_deref().unwrap_or("");
        let summary = file.summary.as_deref().unwrap_or("");
        let _ = writeln!(
            readme,
            "| `{}` | {} | `{}` | {} | {} |",
            file.name,
            file.method,
            file.path.replace('|', "\\|"),
            operation.replace('|', "\\|"),
            summary.replace('|', "\\|")
        );
    }
    let _ = writeln!(readme);
    let _ = writeln!(readme, "## What is included");
    let _ = writeln!(readme);
    let _ = writeln!(readme, "- One request per operation.");
    let _ = writeln!(
        readme,
        "- `{{{{base_url}}}}` as the server. Pass it with `--variable` when you run Hurl."
    );
    let _ = writeln!(
        readme,
        "- Path parameters filled from examples, defaults, or schema samples, then percent-encoded."
    );
    let _ = writeln!(
        readme,
        "- Required query and header parameters. Optional ones are included only when the spec gives an example, default, or `const`."
    );
    let _ = writeln!(
        readme,
        "- A request body from a media-type example when one exists, otherwise a minimal schema sample. Object samples include `required` properties, or every property when nothing is required. `readOnly` properties are omitted."
    );
    let _ = writeln!(
        readme,
        "- A status assertion for the preferred documented success response: `200` if present, otherwise `201`, otherwise the lowest 2xx code. A bare `2XX` wildcard becomes a status range assertion."
    );
    let _ = writeln!(readme);
    let _ = writeln!(
        readme,
        "Cookie parameters, security schemes, callbacks, and links are not turned into requests in v0.1."
    );
    if document.has_webhooks {
        let _ = writeln!(
            readme,
            "This spec also documents webhooks; they are not generated."
        );
    }
    readme
}

fn render_operation(document: &Document, operation: &Operation, file_name: &str) -> Result<String> {
    let mut notes = Vec::new();
    if operation.deprecated {
        notes.push("deprecated: true".to_string());
    }
    let classified = classify_parameters(operation)?;
    if !classified.cookies.is_empty() {
        notes.push(format!(
            "cookie parameters are not emitted in v0.1: {}",
            classified.cookies.join(", ")
        ));
    }

    let path_values = parameter_strings(document, &classified.path)?;
    let url = build_url(&operation.path, &path_values)?;
    let mut headers = parameter_pairs(document, &classified.headers)?;
    let queries = parameter_pairs(document, &classified.queries)?;

    let status = select_status(&operation.responses);
    match &status {
        StatusAssert::Exact(code) => {
            let others = other_success_codes(&operation.responses, Some(*code));
            if !others.is_empty() {
                notes.push(format!(
                    "other documented success statuses: {}",
                    others.join(", ")
                ));
            }
        }
        StatusAssert::Range => {}
        StatusAssert::ExactNonSuccess(code) => {
            notes.push(format!("no 2xx response is documented; asserting {code}"));
        }
        StatusAssert::Any => {
            notes.push("no numeric status is documented; asserting any HTTP status".to_string());
        }
    }

    let response_media = selected_response_media(operation, &status);
    let accept = response_media
        .as_ref()
        .map(|(content_type, _)| base_content_type(content_type))
        .filter(|_| {
            !headers
                .iter()
                .any(|(name, _)| name.eq_ignore_ascii_case("accept"))
        });
    if let Some(content_type) = accept {
        headers.push(("Accept".to_string(), content_type));
    }

    let body = match &operation.request_body {
        Some(request_body) if request_body.content.is_empty() => {
            return Err(Error::spec("request body has no content"));
        }
        Some(request_body) => {
            if !request_body.required {
                notes.push("request body is optional in the spec".to_string());
            }
            let (chosen_type, chosen, alternates) = split_request_media(request_body)?;
            if !alternates.is_empty() {
                notes.push(format!(
                    "request body uses {chosen_type}; also documented: {}",
                    alternates.join(", ")
                ));
            }
            Some(render_body(document, &chosen_type, chosen, &mut headers)?)
        }
        None => None,
    };

    headers.sort_by(|left, right| {
        left.0
            .to_ascii_lowercase()
            .cmp(&right.0.to_ascii_lowercase())
            .then_with(|| left.0.cmp(&right.0))
    });

    let mut lines = Vec::new();
    lines.push(format!(
        "# Generated by spechurl {VERSION}. Do not edit by hand."
    ));
    lines.push(format!("# Source: {}", document.source_name));
    if let Some(operation_id) = &operation.operation_id {
        lines.push(format!("# operationId: {}", one_line(operation_id)));
    }
    lines.push(format!("# {} {}", operation.method, operation.path));
    if let Some(summary) = operation
        .summary
        .as_deref()
        .or(operation.description.as_deref())
    {
        let summary = one_line(summary);
        if !summary.is_empty() {
            lines.push(format!("# {summary}"));
        }
    }
    if !operation.tags.is_empty() {
        lines.push(format!(
            "# tags: {}",
            operation
                .tags
                .iter()
                .map(|tag| one_line(tag))
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }
    for note in &notes {
        lines.push(format!("# note: {note}"));
    }
    let base_url =
        spec::server_hint(&document.servers).unwrap_or_else(|| "https://example.com".to_string());
    lines.push(format!(
        "# Run: hurl --variable base_url={base_url} --test {file_name}"
    ));
    lines.push(String::new());
    lines.push(format!("{} {url}", operation.method));
    for (name, value) in &headers {
        lines.push(format!(
            "{}: {}",
            escape_key(name),
            escape_value_string(value)
        ));
    }
    if !queries.is_empty() {
        lines.push("[Query]".to_string());
        for (name, value) in queries {
            lines.push(format!(
                "{}: {}",
                escape_key(&name),
                escape_value_string(&value)
            ));
        }
    }
    if let Some(body_lines) = body {
        lines.extend(body_lines);
    }
    lines.push(String::new());
    match &status {
        StatusAssert::Exact(code) | StatusAssert::ExactNonSuccess(code) => {
            lines.push(format!("HTTP {code}"));
        }
        StatusAssert::Range | StatusAssert::Any => {
            lines.push("HTTP *".to_string());
        }
    }
    let mut asserts = Vec::new();
    if matches!(status, StatusAssert::Range) {
        asserts.push("status >= 200".to_string());
        asserts.push("status < 300".to_string());
    }
    if let Some((content_type, _)) = response_media {
        let base = base_content_type(&content_type);
        if !base.is_empty() {
            asserts.push(format!(
                "header \"Content-Type\" contains {}",
                quote_hurl(&base)
            ));
        }
    }
    if !asserts.is_empty() {
        lines.push("[Asserts]".to_string());
        lines.extend(asserts);
    }
    Ok(finish(lines))
}

struct Classified<'a> {
    path: Vec<&'a Parameter>,
    queries: Vec<&'a Parameter>,
    headers: Vec<&'a Parameter>,
    cookies: Vec<String>,
}

fn classify_parameters(operation: &Operation) -> Result<Classified<'_>> {
    let mut path = Vec::new();
    let mut queries = Vec::new();
    let mut headers = Vec::new();
    let mut cookies = Vec::new();
    for parameter in &operation.parameters {
        let explicit = has_explicit_sample(
            parameter.schema.as_ref(),
            parameter.example.as_ref(),
            parameter.content.as_ref(),
        );
        match parameter.location.as_str() {
            "path" => path.push(parameter),
            "query" if parameter.required || explicit => queries.push(parameter),
            "header" if parameter.required || explicit => headers.push(parameter),
            "cookie" => cookies.push(parameter.name.clone()),
            "query" | "header" => {}
            other => {
                return Err(Error::spec(format!(
                    "parameter '{}' has unsupported location '{other}'",
                    parameter.name
                )));
            }
        }
    }
    queries.sort_by(|left, right| left.name.cmp(&right.name));
    cookies.sort();
    Ok(Classified {
        path,
        queries,
        headers,
        cookies,
    })
}

fn parameter_strings(
    document: &Document,
    parameters: &[&Parameter],
) -> Result<BTreeMap<String, String>> {
    let mut values = BTreeMap::new();
    for parameter in parameters {
        let sample = sample_parameter(document, parameter)?;
        let mut wire = value_to_wire_string(&sample);
        if wire.is_empty() {
            wire = "example".to_string();
        }
        values.insert(parameter.name.clone(), wire);
    }
    Ok(values)
}

fn parameter_pairs(
    document: &Document,
    parameters: &[&Parameter],
) -> Result<Vec<(String, String)>> {
    let mut pairs = Vec::with_capacity(parameters.len());
    for parameter in parameters {
        let sample = sample_parameter(document, parameter)?;
        pairs.push((parameter.name.clone(), value_to_wire_string(&sample)));
    }
    Ok(pairs)
}

fn sample_parameter(document: &Document, parameter: &Parameter) -> Result<Value> {
    if let Some(example) = &parameter.example {
        return Ok(example.clone());
    }
    if let Some(schema) = &parameter.schema {
        return sample_schema(schema, document, 0, &mut Vec::new());
    }
    if let Some(content) = &parameter.content {
        if let Some((_, media)) = choose_media(content) {
            if let Some(sample) = sample_media(media, document)? {
                return Ok(sample);
            }
        }
    }
    Ok(Value::String("string".to_string()))
}

fn split_request_media(
    body: &crate::spec::RequestBody,
) -> Result<(String, &crate::spec::MediaType, Vec<String>)> {
    let Some((name, media)) = choose_media(&body.content) else {
        return Err(Error::spec("request body has no content"));
    };
    let mut alternates: Vec<String> = body
        .content
        .keys()
        .filter(|candidate| candidate.as_str() != name)
        .cloned()
        .collect();
    alternates.sort();
    Ok((name.to_string(), media, alternates))
}

fn render_body(
    document: &Document,
    content_type: &str,
    media: &crate::spec::MediaType,
    headers: &mut Vec<(String, String)>,
) -> Result<Vec<String>> {
    let Some(sample) = sample_media(media, document)? else {
        return Ok(vec![format!(
            "# note: request body omitted for {content_type} because the spec has no example or schema"
        )]);
    };
    let base = base_content_type(content_type);
    if is_json_content_type(content_type) {
        push_content_type(headers, content_type);
        return Ok(render_json_body(&sample));
    }
    if base == "application/x-www-form-urlencoded" {
        return Ok(render_form_body(&sample));
    }
    if let Some(text) = scalar_text(&sample) {
        push_content_type(headers, content_type);
        return Ok(render_text_body(&text));
    }
    if base.ends_with("+xml") || base == "application/xml" || base.starts_with("text/") {
        push_content_type(headers, content_type);
        return Ok(render_text_body(&value_to_wire_string(&sample)));
    }
    Ok(vec![format!(
        "# note: request body omitted for {content_type} because v0.1 only samples JSON, form, and text bodies"
    )])
}

fn push_content_type(headers: &mut Vec<(String, String)>, content_type: &str) {
    if headers
        .iter()
        .any(|(name, _)| name.eq_ignore_ascii_case("content-type"))
    {
        return;
    }
    headers.push(("Content-Type".to_string(), content_type.to_string()));
}

fn render_json_body(sample: &Value) -> Vec<String> {
    let pretty = serde_json::to_string_pretty(sample).unwrap_or_else(|_| "null".to_string());
    if pretty.contains("{{") {
        let mut lines = vec!["```raw".to_string()];
        lines.extend(pretty.lines().map(str::to_string));
        lines.push("```".to_string());
        return lines;
    }
    pretty.lines().map(str::to_string).collect()
}

fn render_form_body(sample: &Value) -> Vec<String> {
    let mut lines = vec!["[Form]".to_string()];
    match sample {
        Value::Object(fields) => {
            let mut keys: Vec<_> = fields.keys().cloned().collect();
            keys.sort();
            for key in keys {
                lines.push(format!(
                    "{}: {}",
                    escape_key(&key),
                    escape_value_string(&value_to_wire_string(&fields[&key]))
                ));
            }
        }
        other => {
            lines.push(format!(
                "body: {}",
                escape_value_string(&value_to_wire_string(other))
            ));
        }
    }
    lines
}

fn render_text_body(text: &str) -> Vec<String> {
    let simple =
        !text.is_empty() && !text.contains(['\n', '\r', '`', '#', '\\']) && !text.contains("{{");
    if simple {
        return vec![format!("`{text}`")];
    }
    let raw = text.contains("{{");
    let fence = fence_for(text);
    let mut lines = vec![format!("{fence}{}", if raw { "raw" } else { "" })];
    lines.extend(text.lines().map(str::to_string));
    if text.ends_with('\n') {
        lines.push(String::new());
    }
    lines.push(fence);
    lines
}

fn fence_for(text: &str) -> String {
    let mut width = 3;
    loop {
        let fence = "`".repeat(width);
        if !text.contains(&fence) {
            return fence;
        }
        width += 1;
    }
}

fn scalar_text(value: &Value) -> Option<String> {
    match value {
        Value::String(text) => Some(text.clone()),
        Value::Number(number) => Some(number.to_string()),
        Value::Bool(flag) => Some(flag.to_string()),
        Value::Null => Some("null".to_string()),
        _ => None,
    }
}

enum StatusAssert {
    Exact(u16),
    ExactNonSuccess(u16),
    Range,
    Any,
}

fn select_status(responses: &BTreeMap<String, crate::spec::Response>) -> StatusAssert {
    let mut success = Vec::new();
    let mut numeric = Vec::new();
    let mut wildcard = false;
    for code in responses.keys() {
        if let Some(status) = parse_status(code) {
            numeric.push(status);
            if (200..300).contains(&status) {
                success.push(status);
            }
        } else if is_2xx_wildcard(code) {
            wildcard = true;
        }
    }
    if success.contains(&200) {
        return StatusAssert::Exact(200);
    }
    if success.contains(&201) {
        return StatusAssert::Exact(201);
    }
    if let Some(status) = success.iter().min() {
        return StatusAssert::Exact(*status);
    }
    if wildcard {
        return StatusAssert::Range;
    }
    if let Some(status) = numeric.iter().min() {
        return StatusAssert::ExactNonSuccess(*status);
    }
    StatusAssert::Any
}

fn other_success_codes(
    responses: &BTreeMap<String, crate::spec::Response>,
    selected: Option<u16>,
) -> Vec<String> {
    let mut others = Vec::new();
    for code in responses.keys() {
        let trimmed = code.trim();
        if let Some(status) = parse_status(trimmed) {
            if (200..300).contains(&status) && Some(status) != selected {
                others.push(status.to_string());
            }
        } else if is_2xx_wildcard(trimmed) && selected.is_some() {
            others.push(trimmed.to_string());
        }
    }
    others.sort();
    others.dedup();
    others
}

fn selected_response_media(
    operation: &Operation,
    status: &StatusAssert,
) -> Option<(String, crate::spec::MediaType)> {
    let code = match status {
        StatusAssert::Exact(code) | StatusAssert::ExactNonSuccess(code) => code.to_string(),
        StatusAssert::Range => operation
            .responses
            .keys()
            .find(|code| is_2xx_wildcard(code))
            .cloned()?,
        StatusAssert::Any => return None,
    };
    let response = operation.responses.get(&code).or_else(|| {
        operation
            .responses
            .iter()
            .find(|(key, _)| key.trim() == code)
            .map(|(_, response)| response)
    })?;
    let content = response.content.as_ref()?;
    let (name, media) = choose_media(content)?;
    Some((name.to_string(), media.clone()))
}

fn parse_status(code: &str) -> Option<u16> {
    let code = code.trim();
    if code.is_empty() || !code.chars().all(|ch| ch.is_ascii_digit()) {
        return None;
    }
    code.parse().ok()
}

fn is_2xx_wildcard(code: &str) -> bool {
    let code = code.trim();
    code.len() == 3
        && code.as_bytes().first() == Some(&b'2')
        && code[1..].eq_ignore_ascii_case("xx")
}

fn build_url(path: &str, params: &BTreeMap<String, String>) -> Result<String> {
    if path.starts_with("http://") || path.starts_with("https://") {
        return substitute_path(path, params);
    }
    let path = if path.starts_with('/') {
        path.to_string()
    } else {
        format!("/{path}")
    };
    let substituted = substitute_path(&path, params)?;
    Ok(format!("{{{{base_url}}}}{substituted}"))
}

fn substitute_path(path: &str, params: &BTreeMap<String, String>) -> Result<String> {
    let mut out = String::new();
    let mut rest = path;
    while let Some(start) = rest.find('{') {
        out.push_str(&rest[..start]);
        let after = &rest[start + 1..];
        let Some(end) = after.find('}') else {
            return Err(Error::spec(format!("unclosed path parameter in '{path}'")));
        };
        let name = &after[..end];
        if name.is_empty() {
            return Err(Error::spec(format!("empty path parameter in '{path}'")));
        }
        let raw = params
            .get(name)
            .ok_or_else(|| Error::spec(format!("path parameter '{{{name}}}' is not documented")))?;
        out.push_str(&percent_encode(raw));
        rest = &after[end + 1..];
    }
    out.push_str(rest);
    Ok(out)
}

fn percent_encode(value: &str) -> String {
    let mut out = String::new();
    for byte in value.bytes() {
        match byte {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'.' | b'_' | b'~' => {
                out.push(byte as char);
            }
            _ => {
                let _ = write!(out, "%{byte:02X}");
            }
        }
    }
    out
}

fn file_names(document: &Document) -> Vec<String> {
    let mut used = HashSet::new();
    let mut names = Vec::with_capacity(document.operations.len());
    for operation in &document.operations {
        let base = operation_filename(&operation.method, &operation.path);
        let stem = base.trim_end_matches(".hurl");
        let mut name = base.clone();
        if used.contains(&name) {
            let mut suffix = 2;
            loop {
                let candidate = format!("{stem}_{suffix}.hurl");
                if !used.contains(&candidate) {
                    name = candidate;
                    break;
                }
                suffix += 1;
            }
        }
        used.insert(name.clone());
        names.push(name);
    }
    names
}

pub(crate) fn operation_filename(method: &str, path: &str) -> String {
    let method = method.to_ascii_lowercase();
    let trimmed = path.trim_matches('/');
    let mut slug = String::new();
    if trimmed.is_empty() {
        slug.push_str("root");
    } else {
        for ch in trimmed.chars() {
            if ch.is_alphanumeric() {
                for lower in ch.to_lowercase() {
                    slug.push(lower);
                }
            } else if ch != '{' && ch != '}' && !slug.ends_with('_') {
                slug.push('_');
            }
        }
        if slug.ends_with('_') {
            slug.pop();
        }
        if slug.is_empty() {
            slug.push_str("root");
        }
    }
    format!("{method}_{slug}.hurl")
}

fn one_line(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn finish(lines: Vec<String>) -> String {
    let mut text = lines.join("\n");
    if !text.ends_with('\n') {
        text.push('\n');
    }
    text
}

/// Escape a Hurl key-string. Simple tokens are left unchanged.
fn escape_key(input: &str) -> String {
    let mut out = String::new();
    for ch in input.chars() {
        if ch.is_ascii_alphanumeric() || matches!(ch, '_' | '-' | '.' | '[' | ']' | '@' | '$') {
            out.push(ch);
        } else {
            let _ = write!(out, "\\u{{{:x}}}", u32::from(ch));
        }
    }
    out
}

/// Escape a Hurl value-string (header, query, or form value).
///
/// Quotes are literal in this grammar, so values stay unquoted. `#`, `\`, and
/// newlines are escaped. A `{{` sequence is broken up so Hurl does not treat
/// it as a template.
fn escape_value_string(input: &str) -> String {
    let mut out = String::new();
    let chars: Vec<char> = input.chars().collect();
    let mut index = 0;
    while index < chars.len() {
        let ch = chars[index];
        match ch {
            '\\' => out.push_str("\\\\"),
            '#' => out.push_str("\\#"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '{' if chars.get(index + 1) == Some(&'{') => out.push_str("\\u{7b}"),
            _ => out.push(ch),
        }
        index += 1;
    }
    out
}

fn quote_hurl(input: &str) -> String {
    let mut out = String::from("\"");
    for ch in input.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn filenames_are_stable_slugs() {
        assert_eq!(operation_filename("GET", "/pets"), "get_pets.hurl");
        assert_eq!(
            operation_filename("GET", "/pets/{petId}"),
            "get_pets_petid.hurl"
        );
        assert_eq!(operation_filename("DELETE", "/"), "delete_root.hurl");
        assert_eq!(operation_filename("POST", "/a//b"), "post_a_b.hurl");
    }

    #[test]
    fn value_escapes_hash_and_templates() {
        assert_eq!(escape_value_string("a#b"), "a\\#b");
        assert_eq!(escape_value_string("{{name}}"), "\\u{7b}{name}}");
        assert_eq!(escape_key("q"), "q");
        assert_eq!(quote_hurl("application/json"), "\"application/json\"");
    }
}
